dependencies:
  - mongodb=3.4.10
  - python=3.6.5
  - git=2.14.1
  - pip:
    - pymongo==3.6.1
    - pyqt5==5.7.1
    - checksumdir
    - toml
    - autopep8
    - pep8
    - jedi
    - flake8
    - psutil
    - gitpython
    - colorama
