executable = "nuke11.2v3"
schema = "avalon-core:application-1.0"
application_dir = "nuke"
label = "Nuke11.2v3"

[environment]
PYBLISH_GUI = [
        "lite"
    ]
NUKE_PATH = [
  "{AVALON_CORE}/setup/nuke",
  "{PYPE_STUDIO_CONFIG}/setup/nuke/nuke_path"
]
